name: "Excel spreadsheet creator"
description: "Create the SAMM spreadsheet from model files"
author: "SAMM core team"
inputs:
  version:
    description: 'The version to use when generating the spreadsheet'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"